Update to handle multiple inputs and outputs
Cambridge-ICCS/fortran-pytorch-lib pull request #2
Opened 2023-03-28 13:34 UTC by jatkinson1000

These updates should address and close #1 

In the Fortran:
- [ ] Instead of passing an input tensor pass an array of tensors.
- [ ] Get the length of the input array of tensors and pass that to the c++

In the c++:
- [ ] loop over the number of tensors and append (`.push_back`) on to the inputs to the C function.

In the examples:
- [ ] Update so that they still compile and run (make inputs/outputs arrays, and add n_in/out)

In the documentation:
- [ ] Update documentation to reflect these changes (ONLY CHANGES. OTHER DOCS ISSUES ARE FOR ANOTHER ISSUE!)

2023-04-04 09:02 UTC, mondus requested changes
Some more minor comments. Testing is a suggestion to protect your future self so I would be happy to leave that to discretion. Take a look at the try catch loop though.

2023-04-04 09:02 UTC, mondus commented on fortran-pytorch-lib/ts_inference.c
> +    const int nin = 1;
It seems at odds to make this change and then not have a test using multiple inputs. The correct thing to do is to have some unit testing (but that is probably another issue). There should at least be an example for now that allows testing using multiple inputs.

2023-04-06 14:45 UTC, SimonClifford approved these changes
lgtm

2023-05-26 14:37 UTC, jatkinson1000 commented on fortran-pytorch-lib/ctorch.cpp
> +    std::move(*out) = model->forward(inputs_vec).toTensor();
We are casting the output of calling the model to a tensor here, and catching if something goes wrong, so wouldn't be able to test using `isTensor` until after we perform this operation.
As such I think this is OK as is, but willing to discuss in-person and probe further.

2023-05-26 14:43 UTC, jatkinson1000 commented on fortran-pytorch-lib/ctorch.cpp
> +  // TODO: perform this check on all elements(or first and alter rest)?
Removing this line as we are currently only dealing with a single output.
We will need to revisit this in future when looking at multiple outputs in issue #3 , perhaps in a future release?

2023-05-30 09:28 UTC, jatkinson1000 commented on fortran-pytorch-lib/ctorch.cpp
> +    std::move(*out) = model->forward(inputs_vec).toTensor();
See example here: https://github.com/pytorch/pytorch/blob/e380d692dc2c20d711c2155fc580eec30383d301/aten/src/ATen/core/ivalue.h#LL1083C1-L1086C8

We want to check the object we are going to cast is a tensor before doing so. Then modify the else clause to provide something like:
```
std::cerr << "[ERROR]: " << "function torch.jit.module.forward called returning object that is not a tensor" << std::endl;
```

2023-05-30 15:10 UTC, jatkinson1000 commented on fortran-pytorch-lib/ctorch.cpp
> +    std::move(*out) = model->forward(inputs_vec).toTensor();
The documentation for `isTensor` is [here](https://pytorch.org/cppdocs/api/structc10_1_1_i_value.html#_CPPv4NK3c106IValue8isTensorEv) and based on trying to call it from a `torch::Tensor` using, e.g.
```
torch::Tensor LocalTensor;
LocalTensor = *(in[i]);
if (LocalTensor.isTensor()){
...
```
Throws an error with `error: ‘class torch::nn::AnyValue’ has no member named ‘isTensor’` so perhaps it needs calling on an `IValue` or `AnyValue` to see if iot is a Tensor.

Further, in line 174 when we do a `reinterpret_cast` on `inputs` aren't we forcing the code to view `in` as a vector of pointers to Tensors?

Another issue with implementing what we discussed is that I can't work out how `AnyValue`s should be declared. I've tried `torch::AnyValue` and `torch::jit::AnyValue`...

2023-05-31 15:08 UTC, jatkinson1000 commented on fortran-pytorch-lib/ctorch.cpp
> +    std::move(*out) = model->forward(inputs_vec).toTensor();
OK, we now check the `IValues` to ensure that the inputs are all Tensors.
For the output we agreed that there should be a C++ error raised when we try and place them in a Tensor variable if they are not Tensors - a comment has been made to note this in the code.

We may revisit this if we look at multiple outputs in #3

2023-05-31 15:37 UTC, jatkinson1000 commented
Have addressed the above review with collaboration with @mondus and additional documentation.
Requesting re-review.

2023-05-31 16:52 UTC, merged