Add simple example
Cambridge-ICCS/fortran-pytorch-lib pull request #40
Opened 2023-09-27 10:22 UTC by jatkinson1000

Closes #39 

I have added the most basic (whilst remaining somewhat realistinc with a 'Net') example I could think of.

This should be an entry point for users who can see how to couple without having to worry about further details such as row/column major, transposes, stride access etc. which can be introduced in later examples.

At the moment I have made it exercise '0', but we should probably bump it to 1, and ResNet to 2 if we are happy.

2023-09-27 10:57 UTC, ElliottKasoar requested changes
Looks great so far, I've just added a few minor comments.

2023-09-27 10:57 UTC, ElliottKasoar commented on examples/0_SimpleNet/README.md
> +Then from this directory create a virtual environment an install the neccessary python
Very minor typo: neccessary -> necessary

2023-09-27 10:58 UTC, ElliottKasoar commented on examples/0_SimpleNet/README.md
> +You will also likely need to add the location of the `.so` or `.dylib` files to your `LD_LIBRARY_PATH`:
It might be useful to clarify what is being referred to by  `.so` or `.dylib` files?

2023-09-27 15:44 UTC, jatkinson1000 commented on examples/0_SimpleNet/README.md
> +Then from this directory create a virtual environment an install the neccessary python
Done.

2023-09-27 15:52 UTC, jatkinson1000 commented on examples/0_SimpleNet/README.md
> +You will also likely need to add the location of the `.so` or `.dylib` files to your `LD_LIBRARY_PATH`:
Done.

2023-09-27 16:19 UTC, ElliottKasoar requested changes
Thanks for the changes!

Another non-breaking but odd thing is that I get `UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:84.)`, which I didn't think I got before.

2023-09-27 16:19 UTC, ElliottKasoar commented on examples/0_SimpleNet/simplenet_infer_python.py
> +"""Load SimpleNet saved to TorchScript and run inference with ones."""
I think this file needs updating to the new input, as when I run `python3 simplenet_infer_python.py` I get:

```
  input_tensor = torch.ones(batch_size, 5)
tensor([[2., 2., 2., 2., 2.]])
```
rather than the new input/output tensors.

2023-09-27 16:53 UTC, jatkinson1000 commented on examples/0_SimpleNet/simplenet_infer_python.py
> +"""Load SimpleNet saved to TorchScript and run inference with ones."""
Thanks, think that's fixed now -_-

2023-09-28 09:23 UTC, ElliottKasoar approved these changes
All looks good to me!

Final comments: we could add type-hinting to simplenet_infer_python.py, and a warning about the potential for a `"No module named 'numpy'"` warning when running simplenet.py, pt2ts.py or simplenet_infer_python.py, but I'm not sure either of these are essential.

2023-09-28 11:08 UTC, jatkinson1000 commented
Thanks.
Added type hints (somehow missed those).
Numpy isn't used explicitly in any scripts (will be brought in as a dep of torch) and the issue doesn't raise for me.

I'll squash and merge now.

2023-09-28 11:09 UTC, merged